### ISSUE TITLE
Instances Terminate on Dependency Failure

### ISSUE THREAD

**Issue by thalesredteam** [Coalfire-Research/npk#102]
End of Instance output log file:

module.js:682
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /root/compute-node/node_modules/node-pty/build/Release/pty.node)
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/compute-node/node_modules/node-pty/lib/unixTerminal.js:21:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
Completed 68.8 KiB/68.8 KiB (196.4 KiB/s) with 1 file(s) remaining
upload: ../potfiles/i-07cdf8f22850da1a9-output.log to s3://npk-user-data-20200624131317609900000012/us-west-2:35f0f714-3dfa-4baa-b183-204dd4e0c16a/campaigns/5e6e216a-612c-41e9-9fd2-24203c9ba67b/potfiles/i-07cdf8f22850da1a9-output.log
Cloud-init v. 0.7.6 finished at Wed, 24 Jun 2020 13:21:00 +0000. Datasource DataSourceEc2.  Up 128.88 seconds

**Comment by thalesredteam** [comment]
This happened in a clean environment when having reproduced all NPK instructions of setup + using own dict buckets.

**Comment by awhitehatter** [comment]
Thanks, I'm getting a couple of reports of this, I do not know what's causing it. Going to try to duplicate later today.

**Comment by thalesredteam** [comment]
Thanks, let me know when you find anything out.

**Comment by thalesredteam** [comment]
Got a different error in another attempt:

```
module.js:682
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libnode.so.64: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/compute-node/node_modules/node-pty/lib/unixTerminal.js:21:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
Completed 123.1 KiB/123.1 KiB (270.9 KiB/s) with 1 file(s) remaining
upload: ../potfiles/i-00cd2fb87ce558fd9-output.log to s3://npk-user-data-20200624103135850800000012/us-west-2:0b35f4c9-abea-4e48-b9bc-7c1f1c38aab6/campaigns/1fb281a2-9a8a-4a8e-b67c-e89e5884b05a/potfiles/i-00cd2fb87ce558fd9-output.log
Cloud-init v. 0.7.6 finished at Wed, 24 Jun 2020 16:56:18 +0000. Datasource DataSourceEc2.  Up 137.54 seconds
```

**Comment by thalesredteam** [comment]
@awhitehatter Have you had a chance yet?

**Comment by thalesredteam** [comment]
Any updates?

**Comment by awhitehatter** [comment]
I think so, try copying over the components from the public bucket to your bucket(s). 

1. Create a directory called _components_ in your bucket(s)
2. Sync the components over from the shared buckets: 
`aws s3 sync s3://npk-dictionary-west-2-20181029005812750900000002-2/components/ s3://<your bucket(s)>`

**Comment by thalesredteam** [comment]
Worked thanks.
