### ISSUE TITLE
Campaign Create Error / SSO

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#149]
Getting errors when creating campaign with user that authenticates to NPK via SSO.

2021-03-31T02:32:55.467Z    #####-fec1-47dc-8abd-2e8af93e2bfd    INFO    Finished with error UserNotFoundException: User does not exist.
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
  code: 'UserNotFoundException',
  time: 2021-03-31T02:32:55.406Z,
  requestId: '####-1a6c-4ea9-a495-30c6d1a65982',
  statusCode: 400,
  retryable: false,
  retryDelay: 15.040466930704156

**Comment by c6fc** [comment]
This seems to be related to the logging addition in v2, which might not be properly enumerating user information to populate logs with when users come from SSO. I'll work with you via DM to address.
