### ISSUE TITLE
Hardcode Hashcat wrapper package versions

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#58]
Keep getting error below in pot file when running NPK job. 

Error: The module '/root/compute-node/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/compute-node/node_modules/node-pty/lib/unixTerminal.js:21:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
module.js:682
  return process.dlopen(module, path._makeLong(filename));

**Comment by c6fc** [comment]
The hashcat wrapper was originally built for Node8, and the build process is sketchy now since all the lambda functions are using Node12. As a result, selfhost in v2 is being moved to an upstream-sync approach for these components instead of the previous built+upload in order to avoid this problem. v3 will switch off of the component retrieval entirely in favor of a custom AMI now that nvidia doesn't publish them anymore.
